name = "DecayAngles"
uuid = "b554e927-dfdc-487d-b897-432a0f9e843f"
authors = ["Mikhail Mikhasenko <mikhail.mikhasenko@cern.ch>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
AbstractTrees = "0.4.5"
Setfield = "1.1.1"
